### ISSUE TITLE
This is not a real Swagger 2.0 Translation to RAML

### ISSUE THREAD

**Issue by DamianLion** [tcorral/swagger2-to-raml#1]
Would be very glad and happy if it is possible to remove this line in exchange of a real Swagger 2.0 Translation to RAML

`https://apitransformer.com/api/transform?output=raml08`

As api transformer is closed source and we don't know what's happening over there with our API Description

**Comment by Pradeepraj** [comment]
This package uses external source (https://apimatic.io/transformer) to convert the files.
